### ISSUE TITLE
is my install busted or --nocontainer broken?

### ISSUE THREAD

**Issue by juhp** [containers/ramalama#167]
When I try run with `--nocontainer` I get a backtrace:

```
$ ramalama --nocontainer run tiny
Traceback (most recent call last):
  File "/usr/bin/ramalama", line 35, in <module>
    main(sys.argv[1:])
    ~~~~^^^^^^^^^^^^^^
  File "/usr/bin/ramalama", line 20, in main
    ramalama.init_cli()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/ramalama/cli.py", line 82, in init_cli
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/ramalama/cli.py", line 325, in run_cli
    model.run(args)
    ~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/ramalama/model.py", line 101, in run
    exec_cmd(exec_args)
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ramalama/common.py", line 41, in exec_cmd
    return os.execvp(args[0], args)
           ~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 611, in execvp
  File "<frozen os>", line 653, in _execvpe
  File "<frozen os>", line 644, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
```

This is using an install with [my modified spec file](https://download.copr.fedorainfracloud.org/results/petersen/ramalama/fedora-rawhide-aarch64/08053885-python-ramalama/python-ramalama.spec) which is in my test [copr](https://copr.fedorainfracloud.org/coprs/petersen/ramalama/) 

(I first hit this trying to run ramalama inside a toolbox container, but also get it in a vm with `--nocontainer`.)

**Comment by juhp** [comment]
Or is this because  I don't have ollama (etc) installed locally say?

**Comment by ericcurtin** [comment]
@juhp we don't use Ollama directly, we have our own implementation of an Ollama client written from scratch.

It's because you don't have llama.cpp installed on your system, looking at the code, it's trying to exec llama-server and you don't have it:

```
    def serve(self, args):
        symlink_path = self.pull(args)
        exec_args = ["llama-server", "--port", args.port, "-m", symlink_path] + self.common_params
        exec_cmd(exec_args)
```

users who don't use containers are gonna run into this kinda thing all the time. These AI frameworks are complex, --nocontainer is for advanced Linux users and macOS.

Note if you want to use with a GPU, you will likely have to build llama.cpp in a very specific way.

Something that could be a nice contribution is to make this error message clearer, so if someone else tries this in the future they have a more informative message (they can see it's specifically llama-server that it is trying to execute and failing on).

**Comment by rhatdan** [comment]
We have added caught the exception and now add information to tell you that  you need to install llama.cpp.  Hope to have a brew install in place soon, so we could setup this requirement.

Also Mac will now be able to run containers within podman machines and docker machines, to access llama.cpp within containers.
